/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 14
#define LARGE_STATE_COUNT 13
#define SYMBOL_COUNT 31
#define ALIAS_COUNT 0
#define TOKEN_COUNT 24
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LPAREN = 1,
  anon_sym_RPAREN = 2,
  sym_exclaim_prefix = 3,
  sym_question_prefix = 4,
  sym_quote_prefix = 5,
  sym_variable = 6,
  sym_space_reference = 7,
  sym_wildcard = 8,
  sym_boolean_literal = 9,
  sym_special_type_symbol = 10,
  sym_identifier = 11,
  sym_arrow_operator = 12,
  sym_comparison_operator = 13,
  sym_assignment_operator = 14,
  sym_type_annotation_operator = 15,
  sym_rule_definition_operator = 16,
  sym_punctuation_operator = 17,
  sym_arithmetic_operator = 18,
  sym_logic_operator = 19,
  sym_string_literal = 20,
  sym_float_literal = 21,
  sym_integer_literal = 22,
  sym_line_comment = 23,
  sym_source_file = 24,
  sym_expression = 25,
  sym_list = 26,
  sym_prefixed_expression = 27,
  sym_atom_expression = 28,
  sym_operator = 29,
  aux_sym_source_file_repeat1 = 30,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_exclaim_prefix] = "exclaim_prefix",
  [sym_question_prefix] = "question_prefix",
  [sym_quote_prefix] = "quote_prefix",
  [sym_variable] = "variable",
  [sym_space_reference] = "space_reference",
  [sym_wildcard] = "wildcard",
  [sym_boolean_literal] = "boolean_literal",
  [sym_special_type_symbol] = "special_type_symbol",
  [sym_identifier] = "identifier",
  [sym_arrow_operator] = "arrow_operator",
  [sym_comparison_operator] = "comparison_operator",
  [sym_assignment_operator] = "assignment_operator",
  [sym_type_annotation_operator] = "type_annotation_operator",
  [sym_rule_definition_operator] = "rule_definition_operator",
  [sym_punctuation_operator] = "punctuation_operator",
  [sym_arithmetic_operator] = "arithmetic_operator",
  [sym_logic_operator] = "logic_operator",
  [sym_string_literal] = "string_literal",
  [sym_float_literal] = "float_literal",
  [sym_integer_literal] = "integer_literal",
  [sym_line_comment] = "line_comment",
  [sym_source_file] = "source_file",
  [sym_expression] = "expression",
  [sym_list] = "list",
  [sym_prefixed_expression] = "prefixed_expression",
  [sym_atom_expression] = "atom_expression",
  [sym_operator] = "operator",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_exclaim_prefix] = sym_exclaim_prefix,
  [sym_question_prefix] = sym_question_prefix,
  [sym_quote_prefix] = sym_quote_prefix,
  [sym_variable] = sym_variable,
  [sym_space_reference] = sym_space_reference,
  [sym_wildcard] = sym_wildcard,
  [sym_boolean_literal] = sym_boolean_literal,
  [sym_special_type_symbol] = sym_special_type_symbol,
  [sym_identifier] = sym_identifier,
  [sym_arrow_operator] = sym_arrow_operator,
  [sym_comparison_operator] = sym_comparison_operator,
  [sym_assignment_operator] = sym_assignment_operator,
  [sym_type_annotation_operator] = sym_type_annotation_operator,
  [sym_rule_definition_operator] = sym_rule_definition_operator,
  [sym_punctuation_operator] = sym_punctuation_operator,
  [sym_arithmetic_operator] = sym_arithmetic_operator,
  [sym_logic_operator] = sym_logic_operator,
  [sym_string_literal] = sym_string_literal,
  [sym_float_literal] = sym_float_literal,
  [sym_integer_literal] = sym_integer_literal,
  [sym_line_comment] = sym_line_comment,
  [sym_source_file] = sym_source_file,
  [sym_expression] = sym_expression,
  [sym_list] = sym_list,
  [sym_prefixed_expression] = sym_prefixed_expression,
  [sym_atom_expression] = sym_atom_expression,
  [sym_operator] = sym_operator,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_exclaim_prefix] = {
    .visible = true,
    .named = true,
  },
  [sym_question_prefix] = {
    .visible = true,
    .named = true,
  },
  [sym_quote_prefix] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_space_reference] = {
    .visible = true,
    .named = true,
  },
  [sym_wildcard] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_special_type_symbol] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_arrow_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_comparison_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_type_annotation_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_rule_definition_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_punctuation_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_arithmetic_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_logic_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_float_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_integer_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym_prefixed_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_atom_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_operator] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_argument = 1,
  field_prefix = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_argument] = "argument",
  [field_prefix] = "prefix",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_argument, 1},
    {field_prefix, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
};

static const TSCharacterRange sym_variable_character_set_1[] = {
  {0, 0x08}, {0x0e, 0x1f}, {'!', '\''}, {'*', ':'}, {'<', 'Z'}, {'\\', '\\'}, {'^', 'z'}, {'|', '|'},
  {'~', 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(13);
      ADVANCE_MAP(
        '!', 16,
        '"', 8,
        '$', 19,
        '%', 39,
        '&', 20,
        '\'', 18,
        '(', 14,
        ')', 15,
        '-', 29,
        '.', 26,
        ':', 28,
        ';', 48,
        '<', 27,
        '=', 28,
        '>', 40,
        '?', 17,
        'F', 30,
        'T', 33,
        '_', 40,
        ',', 40,
        '@', 40,
        '|', 40,
        '*', 40,
        '+', 40,
        '/', 40,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      if (lookahead != 0 &&
          lookahead != '[' &&
          lookahead != ']' &&
          (lookahead < '{' || '}' < lookahead)) ADVANCE(40);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(42);
      if (lookahead == '\\') ADVANCE(9);
      if (lookahead == '{') ADVANCE(7);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(42);
      if (lookahead == '\\') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(8);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(42);
      if (lookahead == '\\') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(2);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(42);
      if (lookahead == '\\') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(3);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(42);
      if (lookahead == '\\') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(4);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 6:
      if (lookahead == '"') ADVANCE(42);
      if (lookahead == '\\') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(5);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 7:
      if (lookahead == '"') ADVANCE(42);
      if (lookahead == '\\') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(6);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 8:
      if (lookahead == '"') ADVANCE(42);
      if (lookahead == '\\') ADVANCE(9);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead == 'u') ADVANCE(1);
      if (lookahead == 'x') ADVANCE(2);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(8);
      END_STATE();
    case 10:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      END_STATE();
    case 11:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      END_STATE();
    case 12:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_exclaim_prefix);
      if (lookahead == '?') ADVANCE(41);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_question_prefix);
      if (lookahead == '!') ADVANCE(41);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_quote_prefix);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_variable);
      if ((!eof && set_contains(sym_variable_character_set_1, 9, lookahead))) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_space_reference);
      if ((!eof && set_contains(sym_variable_character_set_1, 9, lookahead))) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_boolean_literal);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_special_type_symbol);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '%') ADVANCE(22);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      if ((!eof && set_contains(sym_variable_character_set_1, 9, lookahead))) ADVANCE(40);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-') ADVANCE(40);
      if ((!eof && set_contains(sym_variable_character_set_1, 9, lookahead))) ADVANCE(40);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '.') ADVANCE(40);
      if ((!eof && set_contains(sym_variable_character_set_1, 9, lookahead))) ADVANCE(40);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '.') ADVANCE(25);
      if ((!eof && set_contains(sym_variable_character_set_1, 9, lookahead))) ADVANCE(40);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '<') ADVANCE(24);
      if (lookahead == '-' ||
          lookahead == '=') ADVANCE(40);
      if ((!eof && set_contains(sym_variable_character_set_1, 9, lookahead))) ADVANCE(40);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '=') ADVANCE(40);
      if ((!eof && set_contains(sym_variable_character_set_1, 9, lookahead))) ADVANCE(40);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '>') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      if ((!eof && set_contains(sym_variable_character_set_1, 9, lookahead))) ADVANCE(40);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(32);
      if ((!eof && set_contains(sym_variable_character_set_1, 9, lookahead))) ADVANCE(40);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(21);
      if ((!eof && set_contains(sym_variable_character_set_1, 9, lookahead))) ADVANCE(40);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(34);
      if ((!eof && set_contains(sym_variable_character_set_1, 9, lookahead))) ADVANCE(40);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(35);
      if ((!eof && set_contains(sym_variable_character_set_1, 9, lookahead))) ADVANCE(40);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(31);
      if ((!eof && set_contains(sym_variable_character_set_1, 9, lookahead))) ADVANCE(40);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(31);
      if ((!eof && set_contains(sym_variable_character_set_1, 9, lookahead))) ADVANCE(40);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      if ((!eof && set_contains(sym_variable_character_set_1, 9, lookahead))) ADVANCE(40);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      if ((!eof && set_contains(sym_variable_character_set_1, 9, lookahead))) ADVANCE(40);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(44);
      if ((!eof && set_contains(sym_variable_character_set_1, 9, lookahead))) ADVANCE(40);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_identifier);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      if ((!eof && set_contains(sym_variable_character_set_1, 9, lookahead))) ADVANCE(40);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_identifier);
      if ((!eof && set_contains(sym_variable_character_set_1, 9, lookahead))) ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_logic_operator);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_string_literal);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_float_literal);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_float_literal);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_float_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == '.') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == '.') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(48);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_exclaim_prefix] = ACTIONS(1),
    [sym_question_prefix] = ACTIONS(1),
    [sym_quote_prefix] = ACTIONS(1),
    [sym_variable] = ACTIONS(1),
    [sym_space_reference] = ACTIONS(1),
    [sym_wildcard] = ACTIONS(1),
    [sym_boolean_literal] = ACTIONS(1),
    [sym_special_type_symbol] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_arrow_operator] = ACTIONS(1),
    [sym_comparison_operator] = ACTIONS(1),
    [sym_assignment_operator] = ACTIONS(1),
    [sym_type_annotation_operator] = ACTIONS(1),
    [sym_rule_definition_operator] = ACTIONS(1),
    [sym_punctuation_operator] = ACTIONS(1),
    [sym_arithmetic_operator] = ACTIONS(1),
    [sym_logic_operator] = ACTIONS(1),
    [sym_string_literal] = ACTIONS(1),
    [sym_float_literal] = ACTIONS(1),
    [sym_integer_literal] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(13),
    [sym_expression] = STATE(4),
    [sym_list] = STATE(9),
    [sym_prefixed_expression] = STATE(9),
    [sym_atom_expression] = STATE(9),
    [sym_operator] = STATE(7),
    [aux_sym_source_file_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [sym_exclaim_prefix] = ACTIONS(9),
    [sym_question_prefix] = ACTIONS(9),
    [sym_quote_prefix] = ACTIONS(11),
    [sym_variable] = ACTIONS(13),
    [sym_space_reference] = ACTIONS(13),
    [sym_wildcard] = ACTIONS(15),
    [sym_boolean_literal] = ACTIONS(13),
    [sym_special_type_symbol] = ACTIONS(13),
    [sym_identifier] = ACTIONS(15),
    [sym_arrow_operator] = ACTIONS(17),
    [sym_comparison_operator] = ACTIONS(17),
    [sym_assignment_operator] = ACTIONS(17),
    [sym_type_annotation_operator] = ACTIONS(17),
    [sym_rule_definition_operator] = ACTIONS(17),
    [sym_punctuation_operator] = ACTIONS(17),
    [sym_arithmetic_operator] = ACTIONS(17),
    [sym_logic_operator] = ACTIONS(19),
    [sym_string_literal] = ACTIONS(13),
    [sym_float_literal] = ACTIONS(13),
    [sym_integer_literal] = ACTIONS(15),
    [sym_line_comment] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym_expression] = STATE(2),
    [sym_list] = STATE(9),
    [sym_prefixed_expression] = STATE(9),
    [sym_atom_expression] = STATE(9),
    [sym_operator] = STATE(7),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_RPAREN] = ACTIONS(21),
    [sym_exclaim_prefix] = ACTIONS(26),
    [sym_question_prefix] = ACTIONS(26),
    [sym_quote_prefix] = ACTIONS(29),
    [sym_variable] = ACTIONS(32),
    [sym_space_reference] = ACTIONS(32),
    [sym_wildcard] = ACTIONS(35),
    [sym_boolean_literal] = ACTIONS(32),
    [sym_special_type_symbol] = ACTIONS(32),
    [sym_identifier] = ACTIONS(35),
    [sym_arrow_operator] = ACTIONS(38),
    [sym_comparison_operator] = ACTIONS(38),
    [sym_assignment_operator] = ACTIONS(38),
    [sym_type_annotation_operator] = ACTIONS(38),
    [sym_rule_definition_operator] = ACTIONS(38),
    [sym_punctuation_operator] = ACTIONS(38),
    [sym_arithmetic_operator] = ACTIONS(38),
    [sym_logic_operator] = ACTIONS(41),
    [sym_string_literal] = ACTIONS(32),
    [sym_float_literal] = ACTIONS(32),
    [sym_integer_literal] = ACTIONS(35),
    [sym_line_comment] = ACTIONS(3),
  },
  [STATE(3)] = {
    [sym_expression] = STATE(5),
    [sym_list] = STATE(9),
    [sym_prefixed_expression] = STATE(9),
    [sym_atom_expression] = STATE(9),
    [sym_operator] = STATE(7),
    [aux_sym_source_file_repeat1] = STATE(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(44),
    [sym_exclaim_prefix] = ACTIONS(9),
    [sym_question_prefix] = ACTIONS(9),
    [sym_quote_prefix] = ACTIONS(11),
    [sym_variable] = ACTIONS(13),
    [sym_space_reference] = ACTIONS(13),
    [sym_wildcard] = ACTIONS(15),
    [sym_boolean_literal] = ACTIONS(13),
    [sym_special_type_symbol] = ACTIONS(13),
    [sym_identifier] = ACTIONS(15),
    [sym_arrow_operator] = ACTIONS(17),
    [sym_comparison_operator] = ACTIONS(17),
    [sym_assignment_operator] = ACTIONS(17),
    [sym_type_annotation_operator] = ACTIONS(17),
    [sym_rule_definition_operator] = ACTIONS(17),
    [sym_punctuation_operator] = ACTIONS(17),
    [sym_arithmetic_operator] = ACTIONS(17),
    [sym_logic_operator] = ACTIONS(19),
    [sym_string_literal] = ACTIONS(13),
    [sym_float_literal] = ACTIONS(13),
    [sym_integer_literal] = ACTIONS(15),
    [sym_line_comment] = ACTIONS(3),
  },
  [STATE(4)] = {
    [sym_expression] = STATE(2),
    [sym_list] = STATE(9),
    [sym_prefixed_expression] = STATE(9),
    [sym_atom_expression] = STATE(9),
    [sym_operator] = STATE(7),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(46),
    [anon_sym_LPAREN] = ACTIONS(7),
    [sym_exclaim_prefix] = ACTIONS(9),
    [sym_question_prefix] = ACTIONS(9),
    [sym_quote_prefix] = ACTIONS(11),
    [sym_variable] = ACTIONS(13),
    [sym_space_reference] = ACTIONS(13),
    [sym_wildcard] = ACTIONS(15),
    [sym_boolean_literal] = ACTIONS(13),
    [sym_special_type_symbol] = ACTIONS(13),
    [sym_identifier] = ACTIONS(15),
    [sym_arrow_operator] = ACTIONS(17),
    [sym_comparison_operator] = ACTIONS(17),
    [sym_assignment_operator] = ACTIONS(17),
    [sym_type_annotation_operator] = ACTIONS(17),
    [sym_rule_definition_operator] = ACTIONS(17),
    [sym_punctuation_operator] = ACTIONS(17),
    [sym_arithmetic_operator] = ACTIONS(17),
    [sym_logic_operator] = ACTIONS(19),
    [sym_string_literal] = ACTIONS(13),
    [sym_float_literal] = ACTIONS(13),
    [sym_integer_literal] = ACTIONS(15),
    [sym_line_comment] = ACTIONS(3),
  },
  [STATE(5)] = {
    [sym_expression] = STATE(2),
    [sym_list] = STATE(9),
    [sym_prefixed_expression] = STATE(9),
    [sym_atom_expression] = STATE(9),
    [sym_operator] = STATE(7),
    [aux_sym_source_file_repeat1] = STATE(2),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(48),
    [sym_exclaim_prefix] = ACTIONS(9),
    [sym_question_prefix] = ACTIONS(9),
    [sym_quote_prefix] = ACTIONS(11),
    [sym_variable] = ACTIONS(13),
    [sym_space_reference] = ACTIONS(13),
    [sym_wildcard] = ACTIONS(15),
    [sym_boolean_literal] = ACTIONS(13),
    [sym_special_type_symbol] = ACTIONS(13),
    [sym_identifier] = ACTIONS(15),
    [sym_arrow_operator] = ACTIONS(17),
    [sym_comparison_operator] = ACTIONS(17),
    [sym_assignment_operator] = ACTIONS(17),
    [sym_type_annotation_operator] = ACTIONS(17),
    [sym_rule_definition_operator] = ACTIONS(17),
    [sym_punctuation_operator] = ACTIONS(17),
    [sym_arithmetic_operator] = ACTIONS(17),
    [sym_logic_operator] = ACTIONS(19),
    [sym_string_literal] = ACTIONS(13),
    [sym_float_literal] = ACTIONS(13),
    [sym_integer_literal] = ACTIONS(15),
    [sym_line_comment] = ACTIONS(3),
  },
  [STATE(6)] = {
    [sym_expression] = STATE(11),
    [sym_list] = STATE(9),
    [sym_prefixed_expression] = STATE(9),
    [sym_atom_expression] = STATE(9),
    [sym_operator] = STATE(7),
    [anon_sym_LPAREN] = ACTIONS(7),
    [sym_exclaim_prefix] = ACTIONS(9),
    [sym_question_prefix] = ACTIONS(9),
    [sym_quote_prefix] = ACTIONS(11),
    [sym_variable] = ACTIONS(13),
    [sym_space_reference] = ACTIONS(13),
    [sym_wildcard] = ACTIONS(15),
    [sym_boolean_literal] = ACTIONS(13),
    [sym_special_type_symbol] = ACTIONS(13),
    [sym_identifier] = ACTIONS(15),
    [sym_arrow_operator] = ACTIONS(17),
    [sym_comparison_operator] = ACTIONS(17),
    [sym_assignment_operator] = ACTIONS(17),
    [sym_type_annotation_operator] = ACTIONS(17),
    [sym_rule_definition_operator] = ACTIONS(17),
    [sym_punctuation_operator] = ACTIONS(17),
    [sym_arithmetic_operator] = ACTIONS(17),
    [sym_logic_operator] = ACTIONS(19),
    [sym_string_literal] = ACTIONS(13),
    [sym_float_literal] = ACTIONS(13),
    [sym_integer_literal] = ACTIONS(15),
    [sym_line_comment] = ACTIONS(3),
  },
  [STATE(7)] = {
    [ts_builtin_sym_end] = ACTIONS(50),
    [anon_sym_LPAREN] = ACTIONS(50),
    [anon_sym_RPAREN] = ACTIONS(50),
    [sym_exclaim_prefix] = ACTIONS(52),
    [sym_question_prefix] = ACTIONS(52),
    [sym_quote_prefix] = ACTIONS(50),
    [sym_variable] = ACTIONS(50),
    [sym_space_reference] = ACTIONS(50),
    [sym_wildcard] = ACTIONS(52),
    [sym_boolean_literal] = ACTIONS(50),
    [sym_special_type_symbol] = ACTIONS(50),
    [sym_identifier] = ACTIONS(52),
    [sym_arrow_operator] = ACTIONS(52),
    [sym_comparison_operator] = ACTIONS(52),
    [sym_assignment_operator] = ACTIONS(52),
    [sym_type_annotation_operator] = ACTIONS(52),
    [sym_rule_definition_operator] = ACTIONS(52),
    [sym_punctuation_operator] = ACTIONS(52),
    [sym_arithmetic_operator] = ACTIONS(52),
    [sym_logic_operator] = ACTIONS(50),
    [sym_string_literal] = ACTIONS(50),
    [sym_float_literal] = ACTIONS(50),
    [sym_integer_literal] = ACTIONS(52),
    [sym_line_comment] = ACTIONS(3),
  },
  [STATE(8)] = {
    [ts_builtin_sym_end] = ACTIONS(54),
    [anon_sym_LPAREN] = ACTIONS(54),
    [anon_sym_RPAREN] = ACTIONS(54),
    [sym_exclaim_prefix] = ACTIONS(56),
    [sym_question_prefix] = ACTIONS(56),
    [sym_quote_prefix] = ACTIONS(54),
    [sym_variable] = ACTIONS(54),
    [sym_space_reference] = ACTIONS(54),
    [sym_wildcard] = ACTIONS(56),
    [sym_boolean_literal] = ACTIONS(54),
    [sym_special_type_symbol] = ACTIONS(54),
    [sym_identifier] = ACTIONS(56),
    [sym_arrow_operator] = ACTIONS(56),
    [sym_comparison_operator] = ACTIONS(56),
    [sym_assignment_operator] = ACTIONS(56),
    [sym_type_annotation_operator] = ACTIONS(56),
    [sym_rule_definition_operator] = ACTIONS(56),
    [sym_punctuation_operator] = ACTIONS(56),
    [sym_arithmetic_operator] = ACTIONS(56),
    [sym_logic_operator] = ACTIONS(54),
    [sym_string_literal] = ACTIONS(54),
    [sym_float_literal] = ACTIONS(54),
    [sym_integer_literal] = ACTIONS(56),
    [sym_line_comment] = ACTIONS(3),
  },
  [STATE(9)] = {
    [ts_builtin_sym_end] = ACTIONS(58),
    [anon_sym_LPAREN] = ACTIONS(58),
    [anon_sym_RPAREN] = ACTIONS(58),
    [sym_exclaim_prefix] = ACTIONS(60),
    [sym_question_prefix] = ACTIONS(60),
    [sym_quote_prefix] = ACTIONS(58),
    [sym_variable] = ACTIONS(58),
    [sym_space_reference] = ACTIONS(58),
    [sym_wildcard] = ACTIONS(60),
    [sym_boolean_literal] = ACTIONS(58),
    [sym_special_type_symbol] = ACTIONS(58),
    [sym_identifier] = ACTIONS(60),
    [sym_arrow_operator] = ACTIONS(60),
    [sym_comparison_operator] = ACTIONS(60),
    [sym_assignment_operator] = ACTIONS(60),
    [sym_type_annotation_operator] = ACTIONS(60),
    [sym_rule_definition_operator] = ACTIONS(60),
    [sym_punctuation_operator] = ACTIONS(60),
    [sym_arithmetic_operator] = ACTIONS(60),
    [sym_logic_operator] = ACTIONS(58),
    [sym_string_literal] = ACTIONS(58),
    [sym_float_literal] = ACTIONS(58),
    [sym_integer_literal] = ACTIONS(60),
    [sym_line_comment] = ACTIONS(3),
  },
  [STATE(10)] = {
    [ts_builtin_sym_end] = ACTIONS(62),
    [anon_sym_LPAREN] = ACTIONS(62),
    [anon_sym_RPAREN] = ACTIONS(62),
    [sym_exclaim_prefix] = ACTIONS(64),
    [sym_question_prefix] = ACTIONS(64),
    [sym_quote_prefix] = ACTIONS(62),
    [sym_variable] = ACTIONS(62),
    [sym_space_reference] = ACTIONS(62),
    [sym_wildcard] = ACTIONS(64),
    [sym_boolean_literal] = ACTIONS(62),
    [sym_special_type_symbol] = ACTIONS(62),
    [sym_identifier] = ACTIONS(64),
    [sym_arrow_operator] = ACTIONS(64),
    [sym_comparison_operator] = ACTIONS(64),
    [sym_assignment_operator] = ACTIONS(64),
    [sym_type_annotation_operator] = ACTIONS(64),
    [sym_rule_definition_operator] = ACTIONS(64),
    [sym_punctuation_operator] = ACTIONS(64),
    [sym_arithmetic_operator] = ACTIONS(64),
    [sym_logic_operator] = ACTIONS(62),
    [sym_string_literal] = ACTIONS(62),
    [sym_float_literal] = ACTIONS(62),
    [sym_integer_literal] = ACTIONS(64),
    [sym_line_comment] = ACTIONS(3),
  },
  [STATE(11)] = {
    [ts_builtin_sym_end] = ACTIONS(66),
    [anon_sym_LPAREN] = ACTIONS(66),
    [anon_sym_RPAREN] = ACTIONS(66),
    [sym_exclaim_prefix] = ACTIONS(68),
    [sym_question_prefix] = ACTIONS(68),
    [sym_quote_prefix] = ACTIONS(66),
    [sym_variable] = ACTIONS(66),
    [sym_space_reference] = ACTIONS(66),
    [sym_wildcard] = ACTIONS(68),
    [sym_boolean_literal] = ACTIONS(66),
    [sym_special_type_symbol] = ACTIONS(66),
    [sym_identifier] = ACTIONS(68),
    [sym_arrow_operator] = ACTIONS(68),
    [sym_comparison_operator] = ACTIONS(68),
    [sym_assignment_operator] = ACTIONS(68),
    [sym_type_annotation_operator] = ACTIONS(68),
    [sym_rule_definition_operator] = ACTIONS(68),
    [sym_punctuation_operator] = ACTIONS(68),
    [sym_arithmetic_operator] = ACTIONS(68),
    [sym_logic_operator] = ACTIONS(66),
    [sym_string_literal] = ACTIONS(66),
    [sym_float_literal] = ACTIONS(66),
    [sym_integer_literal] = ACTIONS(68),
    [sym_line_comment] = ACTIONS(3),
  },
  [STATE(12)] = {
    [ts_builtin_sym_end] = ACTIONS(70),
    [anon_sym_LPAREN] = ACTIONS(70),
    [anon_sym_RPAREN] = ACTIONS(70),
    [sym_exclaim_prefix] = ACTIONS(72),
    [sym_question_prefix] = ACTIONS(72),
    [sym_quote_prefix] = ACTIONS(70),
    [sym_variable] = ACTIONS(70),
    [sym_space_reference] = ACTIONS(70),
    [sym_wildcard] = ACTIONS(72),
    [sym_boolean_literal] = ACTIONS(70),
    [sym_special_type_symbol] = ACTIONS(70),
    [sym_identifier] = ACTIONS(72),
    [sym_arrow_operator] = ACTIONS(72),
    [sym_comparison_operator] = ACTIONS(72),
    [sym_assignment_operator] = ACTIONS(72),
    [sym_type_annotation_operator] = ACTIONS(72),
    [sym_rule_definition_operator] = ACTIONS(72),
    [sym_punctuation_operator] = ACTIONS(72),
    [sym_arithmetic_operator] = ACTIONS(72),
    [sym_logic_operator] = ACTIONS(70),
    [sym_string_literal] = ACTIONS(70),
    [sym_float_literal] = ACTIONS(70),
    [sym_integer_literal] = ACTIONS(72),
    [sym_line_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(74), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(13)] = 0,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [26] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_atom_expression, 1, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_atom_expression, 1, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operator, 1, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_operator, 1, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 2, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prefixed_expression, 2, 0, 1),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_prefixed_expression, 2, 0, 1),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 3, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_metta(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
